version: '3'

services:
  app:
    build: .
    container_name: app-Personnel_Report-back_end
    network_mode: host
    command: bash -c "uvicorn main:app --reload"
    env_file:
      - .env
    volumes:
      - ./fastapi_app.db:/app/fastapi_app.db:delegated
